/**
 * Session information for Claude v3 execution tracking.
 */
export interface SessionInfoV3 {
  /** Internal session ID (generated by ADK) */
  id: string
  /** Claude CLI session ID (from --print-session-id) */
  claudeSessionId: string | null
  /** Feature name this session belongs to */
  feature: string
  /** ISO timestamp when session was first created */
  startedAt: string
  /** ISO timestamp of last activity (updated on each execution) */
  lastActivity: string
  /** Current status of the session */
  status: 'active' | 'completed' | 'interrupted'
  /** Whether session can be resumed (requires claudeSessionId and < 24h inactivity) */
  resumable: boolean
  /** Optional execution metadata */
  metadata?: {
    /** Model used (sonnet, opus, haiku) */
    model?: string
    /** Exit code from last execution */
    exitCode?: number
    /** Duration of last execution in milliseconds */
    duration?: number
  }
}

/**
 * Options for executing Claude CLI commands.
 */
export interface ClaudeV3Options {
  /** Model to use for execution */
  model?: 'sonnet' | 'opus' | 'haiku'
  /** Session ID to resume (if omitted, starts new session) */
  resume?: string
  /** Whether to request session ID in output (default: true) */
  printSessionId?: boolean
  /** Timeout in milliseconds (default: 300000 / 5 minutes) */
  timeout?: number
  /** Callback for streaming output chunks */
  onOutput?: (chunk: string) => void
}

/**
 * Result from executing Claude CLI command.
 */
export interface ClaudeV3Result {
  /** Complete stdout output from Claude */
  output: string
  /** Extracted session ID (null if not found) */
  sessionId: string | null
  /** Process exit code */
  exitCode: number
  /** Total execution duration in milliseconds */
  duration: number
}
